name: docker
on:
  push:
    paths:
      - "**/Dockerfile"
env:
  CI_COMMIT: ${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "2"
      - name: Registry login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        run: ./ci/docker-build-push.sh
